version: '3.5'
services:
  # db:
  #   image: postgres:latest
  #   hostname: db
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=rinha
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.15'
  #         memory: '1.0GB'
  db:
    hostname: database
    image: postgres
    command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c fsync=off -c full_page_writes=off'
    ports:
      - '5432:5432'
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: '1.6GB'

  api1:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'

  api2:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.3GB'

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

networks:
  default:
    driver: bridge
    name: rinha