version: '3.5'
services:
  # db:
  #   image: postgres:latest
  #   hostname: db
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=rinha
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.15'
  #         memory: '1.0GB'
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: '1.9GB'

  api1:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  api2:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

networks:
  default:
    driver: bridge
    name: rinha